version: 1
disable_existing_loggers: false

formatters:
    short:
        format: "%(asctime)s | %(levelname)s | %(message)s"
    
    long:
        format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: long
        stream: ext://sys.stdout
    
    file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: short
        filename: glyculator.log
        maxBytes: 1000000
        backupCount: 3
        encoding: utf8

    test:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: long
        filename: test_debug.log
        maxBytes: 1000000
        backupCount: 1
        encoding: utf8

loggers:
    src:
        handlers: [file, test]
    tests:
        handlers: [test]

root:
    level: DEBUG